id = "elderberry"
name = "Elderberry"
schema_version = 1
version = "0.1.0"
authors = ["Jakka Prihatna <jprihatna@gmail.com>"]
description = "ğŸ« A dark purplish color scheme for Zed"
repository = "https://github.com/IronGeek/zed-theme-elderberry"
